version: 2
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.8
jobs:
  # build:
  #   docker:
  #     - image: node:8-alpine
  #   steps:
  #     - checkout
  #     - run: echo "Checked out, ready to install dependencies."
  #     - run: npm install
  #     - run: mkdir -p my_workspace
  #     - run: apk add ca-certificates
  #     - run: echo "Dependencies installed successfully." > my_workspace/echo-output
  #     - persist_to_workspace:
  #         root: my_workspace
  #         paths:
  #           - echo-output
  test:
    machine: true
    steps:
      - run: git clone https://github.com/nate01776/smart-calculator-backend.git /home/circleci/tests/to_run
      - run: docker run -v="/home/circleci/tests/to_run/tests":/project -v="/home/circleci/tests/reports/junit":/reports -e LICENSE_SERVER="54.184.95.50:1099" -e COMMAND_LINE="-ehttp://54.185.226.137:8050 '-f/reports' '-RJUnit-style HTML Report' /project/smart-calculator-readyapi-project.xml" -it smartbear/ready-api-soapui-testrunner:latest
      - store_artifacts:
          path: /home/circleci/tests/reports
      - store_test_results: 
          path: /home/circleci/tests/reports
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
      - validate_deployment:
          jobs:
            - test:
              requires:
                - build
