version: 2
jobs:
  build:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      # - run: echo "Checked out, ready to install dependencies."
      # - run: npm install
      # - run: mkdir -p my_workspace
      # - run: apk add ca-certificates
      # - run: echo "Dependencies installed successfully." > my_workspace/echo-output
      # - persist_to_workspace:
      #     root: my_workspace
      #     paths:
      #       - echo-output
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install curl
      - run: ls ./tests
      - run: curl -X POST -L --basic --user "admin:testengine" -F "file=@./tests/calc_project.zip;type=application/zip" "http://34.220.244.21:8085/api/v1/testjobs/?environment=remote_actual_v2&async=false"
      # - run: docker run -v="/home/circleci/tests/to_run/tests":/project -v="/home/circleci/tests/reports/junit":/reports -e LICENSE_SERVER="54.184.95.50:1099" -e COMMAND_LINE="-ehttp://54.185.226.137:8050 '-f/reports' '-RJUnit-style HTML Report' /project/smart-calculator-readyapi-project.xml" -it smartbear/ready-api-soapui-testrunner:latest
      - store_artifacts:
          path: /home/circleci/tests/reports
          prefix: /test_results
      - store_test_results: 
          path: /home/circleci/tests/reports
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - test:
          requires:
            - build