version: 2
jobs:
  one:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: npm install
      - run: sleep 25
  two:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: npm install
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
